# Temporal Difference Prediction

# TD Control Task : State Action Reward State Action (SARSA)

In [ ]:
import gym
import random
import pandas as pd

In [ ]:
#Now, we create the Frozen Lake environment using Gym:
env = gym.make('FrozenLake-v1')

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(

In [ ]:
#Initialize the discount factor 𝛾, the learning rate 𝛼,
alpha = 0.85
gamma = 0.90

#and the epsilon value:
epsilon = 0.8

In [ ]:
#Set the number of episodes and number of time steps in the episode:
num_episodes = 50000
num_timesteps = 1000

In [ ]:
#define a random policy to choose random actions
def random_policy():
  return env.action_space.sample()

In [ ]:
env.action_space
#Displays count of number of actions : left, right, top, down

Discrete(4)

# TD Prediction

In [ ]:
#Initialising the state values to zero.
#Create a empty dictionary : for storing the value of states (16 states, 4x4 grid)
v = {}
for s in range (env.observation_space.n):
  #Cannot make the observation space discrete, since it is 5x5 continous space
  v[s]=0.0

In [ ]:
#Compute the policy
#For each episode:
for i in range(num_episodes): #50000
#Initialize the state by resetting the environment:
    s = env.reset() #reset the frozenlake environment
#For each step in the episode:
    for t in range(num_timesteps): #1000
# Select an action according to the random policy
        a = random_policy()
#Perform the selected action and store the next state information:
        s_, r, done, _ = env.step(a)
#Compute the value of state as
        v[s] += alpha * (r + gamma * v[s_]-v[s]) # TD update rule
        #print(v[(s)])
        s = s_
        #a = a_
#If the current state is the terminal state, then break:
        if done: #Check for terminal state
            break

/usr/local/lib/python3.10/dist-packages/gym/utils/passive_env_checker.py:241: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):

In [ ]:
df = pd.DataFrame(list(v.items()), columns=['state', 'value'])

In [ ]:
df

    state         value
0       0  5.463614e-05
1       1  2.532039e-09
2       2  1.788819e-05
3       3  2.263524e-09
4       4  1.377290e-02
5       5  0.000000e+00
6       6  1.016433e-01
7       7  0.000000e+00
8       8  2.242932e-03
9       9  5.903575e-01
10     10  1.155947e-01
11     11  0.000000e+00
12     12  0.000000e+00
13     13  1.053783e-01
14     14  6.631779e-01
15     15  0.000000e+00

# SARSA

In [ ]:
# Now, let's define the epsilon-greedy policy. We generate a random number from
# the uniform distribution and if the random number is less than epsilon, we select the
# random action, else we select the best action that has the maximum Q value:
def epsilon_greedy(state, epsilon):
    if random.uniform(0,1) < epsilon:
        return env.action_space.sample()
    else:
        return max(list(range(env.action_space.n)), key = lambda x:Q[(state,x)])

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
#Let's define the dictionary for storing the Q value of the state-action pair and
#initialize the Q value of all the state-action pairs to 0.0:
Q = {}
for s in range(env.observation_space.n):
    for a in range(env.action_space.n):
        Q[(s,a)] = 0.0

In [ ]:
#Compute the policy
#For each episode:
for i in range(num_episodes):
#Initialize the state by resetting the environment:
    s = env.reset()
#Select the action using the epsilon-greedy policy:
    a = epsilon_greedy(s,epsilon)
#For each step in the episode:
    for t in range(num_timesteps):
#Perform the selected action and store the next state information:
        s_, r, done, _ = env.step(a)
#Select the action 𝑎′ in the next state 𝑠′using the epsilon-greedy policy:
        a_ = epsilon_greedy(s_,epsilon)
#Compute the Q value of the state-action pair as
        Q[(s,a)] += alpha * (r + gamma * Q[(s_,a_)]-Q[(s,a)])
        #print(Q[(s,a)])
# Update s=s' (update the next state s' to the current state s)
        s = s_
        a = a_
#If the current state is the terminal state, then break:
        if done:
            break

In [ ]:
df = pd.DataFrame(list(Q.items()), columns=['state', 'value'])

In [ ]:
df

      state     value
0    (0, 0)  0.000255
1    (0, 1)  0.000368
2    (0, 2)  0.000290
3    (0, 3)  0.000157
4    (1, 0)  0.000786
..      ...       ...
59  (14, 3)  0.111061
60  (15, 0)  0.000000
61  (15, 1)  0.000000
62  (15, 2)  0.000000
63  (15, 3)  0.000000

[64 rows x 2 columns]

# Q Learning

In [ ]:
import numpy as np

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)

In [ ]:
#Compute the policy
#For each episode:
for i in range(num_episodes):
#Initialize the state by resetting the environment:
    s = env.reset()
#For each step in the episode:
    for t in range(num_timesteps):
#Select the action using the epsilon-greedy policy:
        a = epsilon_greedy(s,epsilon)
#Perform the selected action and store the next state information:
        s_, r, done, _ = env.step(a)
#Select the action 𝑎′ that has the maximum Q value in the next state 𝑠′:
        a_ = np.argmax([Q[(s_,a)] for a in range(env.action_space.n)])
#Compute the Q value of the state-action pair as
        Q[(s,a)] += alpha * (r + gamma * Q[(s_,a_)]-Q[(s,a)])
        #print(Q[(s,a)])
# Update s=s' (update the next state s' to the current state s)
        s = s_
        #a = a_
#If the current state is the terminal state, then break:
        if done:
            break

In [ ]:
df = pd.DataFrame(list(Q.items()), columns=['state', 'value'])

In [ ]:
df

      state     value
0    (0, 0)  0.355570
1    (0, 1)  0.374335
2    (0, 2)  0.363719
3    (0, 3)  0.345184
4    (1, 0)  0.050034
..      ...       ...
59  (14, 3)  0.703300
60  (15, 0)  0.000000
61  (15, 1)  0.000000
62  (15, 2)  0.000000
63  (15, 3)  0.000000

[64 rows x 2 columns]